name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image One
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/my-docker-image-one ./second-folder/

    - name: Build Docker image Two
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/my-docker-image-two ./first-folder/

    - name: Log in to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

    - name: Push Docker image One to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/my-docker-image-one

    - name: Push Docker image Two to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/my-docker-image-two
